src/Entity/Word.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WordRepository")
 */
class Word
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $from_word;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $to_translation;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\WordsList", inversedBy="words")
     * @ORM\JoinColumn(nullable=false)
     */
    private $words_list;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFromWord(): ?string
    {
        return $this->from_word;
    }

    public function setFromWord(string $from_word): self
    {
        $this->from_word = $from_word;

        return $this;
    }

    public function getToTranslation(): ?string
    {
        return $this->to_translation;
    }

    public function setToTranslation(string $to_translation): self
    {
        $this->to_translation = $to_translation;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getWordsList(): ?WordsList
    {
        return $this->words_list;
    }

    public function setWordsList(?WordsList $words_list): self
    {
        $this->words_list = $words_list;

        return $this;
    }
}

src/Entity/WordsList.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WordsListRepository")
 */
class WordsList
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Word", mappedBy="words_list", orphanRemoval=true)
     */
    private $words;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="wordsLists")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $noteBookColor;

    public function __construct()
    {
        $this->words = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Word[]
     */
    public function getWords(): Collection
    {
        return $this->words;
    }

    public function addWordId(Word $wordId): self
    {
        if (!$this->words->contains($wordId)) {
            $this->words[] = $wordId;
            $wordId->setWordsList($this);
        }

        return $this;
    }

    public function removeWordId(Word $wordId): self
    {
        if ($this->words->contains($wordId)) {
            $this->words->removeElement($wordId);
            // set the owning side to null (unless already changed)
            if ($wordId->getWordsList() === $this) {
                $wordId->setWordsList(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getNoteBookColor(): ?string
    {
        return $this->noteBookColor;
    }

    public function setNoteBookColor(string $noteBookColor): self
    {
        $this->noteBookColor = $noteBookColor;

        return $this;
    }
}

src/Form/WordsListType.php
<?php

namespace App\Form;

use App\Entity\WordsList;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WordsListType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add("save", SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => WordsList::class,
        ]);
    }
}

src/Controller/WordsListController.php
<?php

namespace App\Controller;

use App\Entity\Word;
use App\Entity\WordsList;
use App\Entity\User;
use App\Form\WordsListType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\Security\Core\User\UserInterface;

class WordsListController extends AbstractController
{
    /**
     * @Route("/list", name="words_list")
     */
    public function index()
    {
        $repository = $this->getDoctrine()->getRepository(WordsList::class);

        $user       = $this->container->get('security.token_storage')->getToken()->getUser();
        $userId     = $user->getId();

        // get the number of lists
        $listNumber = $repository->countUserLists($userId);

        // get all the lists of the current user
        $lists = $repository->getUserLists($userId);

        return $this->render('words_list/wordslist.html.twig', [
            'controller_name' => 'WordsListController',
            'listNumber'      => $listNumber,
            'lists'           => $lists,
        ]);
    }

    /**
     * @Route("/list/new", name="new_list", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $wordsList = new WordsList();
        $user = $this->container->get('security.token_storage')->getToken()->getUser();
        $wordsList->setUser($user);

        // apply a random notebook color
        $classes = ['blueNotebook', 'redNotebook', 'yellowNotebook'];
        // shuffle the colors
        shuffle($classes);
        // get only the first class
        $class = array_slice($classes, 0, 1);

        $wordsList->setNoteBookColor($class[0]);
        $form = $this->createForm(WordsListType::class, $wordsList);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($wordsList);
            $entityManager->flush();

            return $this->redirectToRoute('words_list');
        }

        return $this->render('words_list/new_list.html.twig', [
            'wordsList' => $wordsList,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/list/{id}", name="show_list", methods={"GET","POST"})
     */
    public function show(Request $request, WordsList $list): Response
    {
        $repository = $this->getDoctrine()->getRepository(Word::class);
        $words = $repository->findByWordsListId($list->getId());

        $form = $this->createForm(WordsListType::class, $list);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('show_list', [
                'id' => $list->getId(),
            ]);
        }

        return $this->render('words_list/show_list.html.twig', [
            'list'  => $list,
            'words' => $words,
            'form'  => $form->createView(),
        ]);
    }

    /**
     * @Route("/list/delete/{id}", name="delete_list", methods={"DELETE"})
     */
    public function delete(Request $request, WordsList $list): Response
    {
        if ($this->isCsrfTokenValid('delete'.$list->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($list);
            $entityManager->flush();
        }

        return $this->redirectToRoute('words_list');
    }
}

templates/words_list/_delete_form.html.twig
<form method="post" action="{{ path('delete_list', {'id': list.id}) }}">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ list.id) }}">

    <button class="deleteButton"><img src="{{ asset('images/rubbish-bin-delete-button.png') }}" /></button>
</form>

templates/words_list/_form.html.twig
{{ form_start(form) }}
    <div>
        {{ form_label(form.name, "Nom de la liste") }}
        {{ form_widget(form.name) }}
    </div>

    {{ form_widget(form.save, { 'label': 'Valider' }) }}
{{ form_end(form) }}

templates/words_list/new_list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle liste{% endblock %}

{% block body %}

    {{ include('default/_navbar.html.twig') }}

    <h1>Créer une liste</h1>

    <div class="addListAddWord">
        <a href="{{ path('words_list') }}"><img src="{{ asset('images/back.png') }}" alt="retour"/>Retour</a>
        {{ include('words_list/_form.html.twig') }}
        <img class="flag" src="{{ asset('images/flag.png') }}" alt="flag"/>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/responsive.js') }}"></script>
    <script src="{{ asset('js/addListAddWord.js') }}"></script>
{% endblock %}

templates/words_list/show_list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes mots - {{ list.name }}{% endblock %}
{% block script %}
    <script src="https://kit.fontawesome.com/97f34d6c2d.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/style.css') }}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
{% endblock %}

{% block body %}

    {{ include('default/_navbar.html.twig') }}

    <h1>Mes mots</h1>

    <div class="listsContainer">
        {% set borderColor = '' %}
        {% if list.noteBookColor == 'redNotebook' %}
            {% set borderColor = 'redBorder' %}
        {% elseif list.noteBookColor == 'yellowNotebook' %}
            {% set borderColor = 'yellowBorder' %}
        {% else %}
            {% set borderColor = 'blueBorder' %}
        {% endif %}

        <div class="headerQuiz">
            <a href="{{ path('words_list') }}"><img src="{{ asset('images/back.png') }}" alt="retour"/>Retour</a>
            <h1 class="{{ borderColor }}">{{ list.name }}</h1>
        </div>

        {% if words|length == 0 %}

            <div class="noWordNoListDiv">
                <p>Vous n'avez pas encore de mot, ajoutez-en !</p>
                <a href="{{ path('add_words', {'id': list.id}) }}"><img src="{{ asset('images/plus-symbol.png') }}" /></a>
            </div>

        {% else %}
            <div class="wordsTables">
                <table class="tableHeader">
                    <tbody>
                    <tr>
                        <td>Mot</td>
                    </tr>
                    <tr>
                        <td>Traduction</td>
                    </tr>
                    </tbody>
                </table>
                <table class="tableBody">
                    <tbody>
                        <tr>
                            {% set i = 1 %}
                            {% for word in words %}
                                <td class="tdHover{{ i }}">
                                    <a href="{{ path('show_word', {'id': word.id}) }}">
                                        <p>{{ i }}</p>
                                        <p>{{ word.fromWord }}</p>
                                    </a>
                                </td>
                            {% set i = i+1 %}
                            {% endfor %}
                        </tr>
                        <tr>
                            {% set i = 1 %}
                            {% for word in words %}
                                <td class="tdHover{{ i }}">
                                    <a href="{{ path('show_word', {'id': word.id}) }}">{{ word.toTranslation }}</a>
                                </td>
                                {% set i = i+1 %}
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>
            </div>
        {% endif %}

        <div class="buttonsGroup">

            {% if words|length != 0 %}
                <a class="addButton" href="{{ path('add_words', {'id': list.id}) }}"><img src="{{ asset('images/plus-symbol.png') }}" /></a>
            {% endif %}

            <div id="editModal" class="modal">
                <h3>Modifier la liste</h3>
                {{ include('words_list/_form.html.twig', {'button_label': 'Modifier'}) }}
            </div>
            <a class="editButton" href="#editModal" rel="modal:open"><img src="{{ asset('images/pencil-edit-button.png') }}" /></a>

            <!-- Delete modal hidden and showed on click on the form button -->
            <div id="deleteModal" class="modal">
                <h3>Supprimer la liste</h3>
                <p>Êtes-vous sûr(e) de vouloir supprimer la liste <em>{{ list.name }}</em> ?</p>
                <div>
                    <button class="yesDeleteButton">Oui</button>
                    <a href="#close-modal" rel="modal:close" class="noDeleteButton">Non</a>
                </div>
            </div>
            <a class="deleteButtonModal" href="#deleteModal" rel="modal:open"><img src="{{ asset('images/rubbish-bin-delete-button.png') }}" /></a>
            <!-- Fin modale -->

            {{ include('words_list/_delete_form.html.twig') }}
            <button class="paramButton"><img src="{{ asset('images/dots.png') }}" /></button>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    <script src="{{ asset('js/responsive.js') }}"></script>
    <script src="{{ asset('js/wordslistButtons.js') }}"></script>
    <script src="{{ asset('js/addListAddWord.js') }}"></script>
    <script src="{{ asset('js/wordLink.js') }}"></script>
{% endblock %}

templates/words_list/wordslist.html.twig
{% extends "base.html.twig" %}

{% block body %}
    {{ include('default/_navbar.html.twig') }}

    <h1>Mes listes de mots</h1>

    <div class="listsContainer">
        {% if listNumber == 0 %}
            <div class="noWordNoListDiv">
                <p>Vous n'avez pas encore de liste, ajoutez-en !</p>
                <a href="{{ path('new_list') }}"><img src="{{ asset('images/plus-symbol.png') }}" /></a>
            </div>

        {% else %}
            <ul>
                {% for list in lists %}
                    <li class="flexColumn">
                        <a href="{{ path('show_list', {'id': list.id}) }}">
                            {% if list.noteBookColor == 'redNotebook' %}
                                <img src="{{ asset('images/notebook_red.png') }}"/>
                            {% elseif list.noteBookColor == 'yellowNotebook' %}
                                <img src="{{ asset('images/notebook_yellow.png') }}"/>
                            {% else %}
                                <img src="{{ asset('images/notebook_blue.png') }}"/>
                            {% endif %}

                            <span>{{ list.name }}</span>
                        </a>
                    </li>
                {% endfor %}
            </ul>

            <a class="addButtonCorner" href="{{ path('new_list') }}"><img src="{{ asset('images/plus-symbol.png') }}" /></a>
        {% endif %}
    </div>

{% endblock %}